### ISSUE TITLE
Batch file removes current mods installed.

### ISSUE THREAD

**Issue by MutantRabbit767** [TimeIsUnending/TF2-Auto-Matchmaking-Mod#1]
Small issue while installing:
When running the batch file inside of the installation folder, it removed all my current northstar mods. Probably due to line 11 in the batch file. How nessacary is it for this to happen? For those using VTOL, just download the auto matchmaking mod from the thunderstore and disable all the other northstar mods to save some time reinstalling.

thanks again for the mod though, it really is awesome.

**Comment by TimeIsUnending** [comment]
I am going to be making a new installer soon, I know we already talked about this issue in the discord but I'm putting this here just for reference.
